name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy -- -D warnings

  build:
    needs: lint_and_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Build
        run: cargo build --release --verbose
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: built-binary-x86_64
          path: target/release/ticket-bot

  build_aarch64:
    needs: lint_and_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Add AArch64 Target
        run: rustup target add aarch64-linux-android
      - name: Install Android NDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip android-ndk-r26b-linux.zip
          mv android-ndk-r26b $HOME/android-ndk
      - name: Set Up Environment Variables
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
          echo "CC_aarch64_linux_android=aarch64-linux-android24-clang" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android24-clang" >> $GITHUB_ENV
      - name: Build for AArch64 (Android)
        run: cargo build --release --target aarch64-linux-android --verbose
      - name: Upload AArch64 Binary
        uses: actions/upload-artifact@v4
        with:
          name: built-binary-aarch64
          path: target/aarch64-linux-android/release/ticket-bot
