name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy -- -D warnings

  build:
    needs: lint_and_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Build
        run: cargo build --release --verbose
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: built-binary-x86_64
          path: target/release/ticket-bot

  build_aarch64:
    needs: lint_and_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        run: |
          cargo install cross
      - name: Build for AArch64 (Linux)
        run: cross build --release --target aarch64-unknown-linux-gnu --verbose
      - name: Upload AArch64 Binary
        uses: actions/upload-artifact@v4
        with:
          name: built-binary-aarch64
          path: target/aarch64-unknown-linux-gnu/release/ticket-bot
